### ISSUE TITLE
CRIM Forum Needs to recognize and link to "CRIM_Mass_ + ID" as well as" CRIM_Model + ID"

### ISSUE THREAD

**Issue by RichardFreedman** [CRIM-Project/CRIM-online#5]
The [Forum code](https://github.com/CRIM-Project/CRIM-online/blob/2359b5f8fb89dc38d6b543ff17487c13c027cf85/crim/views/forum.py#L137) currently only 'looks for' CRIM Models.  We also need to have automatic links to CRIM Masses.

I think we need to add something that will thus include:

CRIM_Mass_0001  [That is, the entire Mass]
CRIM_Mass_0001.1  [That is, the first movement]
CRIM_Mass_0001.2 [The second movement]
etc

See [Line 128](https://github.com/CRIM-Project/CRIM-online/blob/2359b5f8fb89dc38d6b543ff17487c13c027cf85/crim/views/forum.py#L128)
And [Line 136](https://github.com/CRIM-Project/CRIM-online/blob/2359b5f8fb89dc38d6b543ff17487c13c027cf85/crim/views/forum.py#L136)

**Comment by RichardFreedman** [comment]
I think the places are:

- [Line 128](https://github.com/CRIM-Project/CRIM-online/blob/2359b5f8fb89

dc38d6b543ff17487c13c027cf85/crim/views/forum.py#L128)
[Line 136](https://github.com/CRIM-Project/CRIM-online/blob/2359b5f8fb89dc38d6b543ff17487c13c027cf85/crim/views/forum.py#L136)


And

**Comment by mjwalter** [comment]
Implemented!
